### ISSUE TITLE
Unable to create a connection for a local user.

### ISSUE THREAD

**Issue by Shersticklock** [jborean93/pypsrp#102]
### **Overview**
Unable to create a connection for a local user located on a host that is in the domain.

I tried to connect on **myhost** via psrp:
    

```
client = Client(myhost, username=myuser, password=mypassword, ssl=False, connection_timeout=2)
script = r'whoami'
client.execute_ps(script)
```

**myuser** is a local user located on **myhost**.
**myhost** is on a domain.

### **Expected behavior**
Remoting connection is successful.

### **Actual behavior**
`pypsrp.exceptions.AuthenticationError: Failed to authenticate the user myuser with negotiate`

**Comment by jborean93** [comment]
What’s the full error message including the stack trace. Is the user part of the local administrators group or part of the remote users group.

**Comment by Shersticklock** [comment]
`
Traceback (most recent call last):`
  `File "1.py", line 4, in <module>`
  `  client.execute_ps(script)`
  `File "/usr/local/lib/python2.7/site-packages/pypsrp/client.py", line 193, in execute_ps`
   ` with RunspacePool(self.wsman, configuration_name=configuration_name) as pool:`
 ` File "/usr/local/lib/python2.7/site-packages/pypsrp/powershell.py", line 205, in __enter__`
  `  self.open()`
  `File "/usr/local/lib/python2.7/site-packages/pypsrp/powershell.py", line 513, in open`
   ` self.shell.open(options, open_content)`
  `File "/usr/local/lib/python2.7/site-packages/pypsrp/shell.py", line 204, in open`
   ` option_set=options)`
  `File "/usr/local/lib/python2.7/site-packages/pypsrp/wsman.py", line 270, in create`
    `option_set, selector_set, timeout)`
  `File "/usr/local/lib/python2.7/site-packages/pypsrp/wsman.py", line 389, in invoke`
    `response = self.transport.send(xml)`
  `File "/usr/local/lib/python2.7/site-packages/pypsrp/wsman.py", line 729, in send`
    `self._send_request(prep_request)`
 ` File "/usr/local/lib/python2.7/site-packages/pypsrp/wsman.py", line 787, in _send_request`
    `% (self.username, self.auth))`
`pypsrp.exceptions.AuthenticationError: Failed to authenticate the user myuser with negotiate`

***myuser*** member of ***Remote Desktop User*** but not a member of the ***local administrators group***

**Comment by jborean93** [comment]
Can you use those same credentials when you connect through PowerShell itself? Has the account, or a group it is a member off been granted network logon rights, or has it potentially been denied network logon rights?

**Comment by Shersticklock** [comment]
I added the ***myuser*** to the group ***Remote Management Users***
Powershell:
`$cred = Get-Credential `
`Enter-PSSession -ComputerName myhost -Credential $cred`
`whoami`
Its working for me.
but psrp:
`Traceback (most recent call last):`
`File "1.py", line 4, in <module>`
`client.execute_ps(script)`
`File "/usr/local/lib/python2.7/site-packages/pypsrp/client.py", line 193, in execute_ps`
`with RunspacePool(self.wsman, configuration_name=configuration_name) as pool:`
`File "/usr/local/lib/python2.7/site-packages/pypsrp/powershell.py", line 205, in __enter__`
`self.open()`
`File "/usr/local/lib/python2.7/site-packages/pypsrp/powershell.py", line 513, in open`
`self.shell.open(options, open_content)`
`File "/usr/local/lib/python2.7/site-packages/pypsrp/shell.py", line 204, in open`
`option_set=options)`
`File "/usr/local/lib/python2.7/site-packages/pypsrp/wsman.py", line 270, in create`
`option_set, selector_set, timeout)`
`File "/usr/local/lib/python2.7/site-packages/pypsrp/wsman.py", line 389, in invoke`
`response = self.transport.send(xml)`
`File "/usr/local/lib/python2.7/site-packages/pypsrp/wsman.py", line 729, in send`
`self._send_request(prep_request)`
`File "/usr/local/lib/python2.7/site-packages/pypsrp/wsman.py", line 787, in _send_request`
`% (self.username, self.auth))`
`pypsrp.exceptions.AuthenticationError: Failed to authenticate the user myuser with negotiate`

**Comment by jborean93** [comment]
If PowerShell works but this doesn't then the next step would be to look at the Security even logs to find the reason and sub reason as to why Windows rejected the failure. This would help to narrow down why it's not working with this library.

**Comment by Shersticklock** [comment]
i rebooted the host :) and it worked for me, but if i want to change the password for my user
`client = Client(myhost, username=myuser, password=mypassword, ssl=False, connection_timeout=2)`
`script = r'net user myuser mypassword'`
`client.execute_ps(script)`

i get an ERROR:
System error 5 has occurred.

Access is denied.

Apparently I need local administrator rights.


Thank you for your help @jborean93

**Comment by jborean93** [comment]
To change the password without specifying the existing password definitely needs admin rights. I’m not sure how to do that in a command but considering you solved the problem I’ll close this issue.
