### ISSUE TITLE
ps.add_cmdlet can't input -Confirm:$false

### ISSUE THREAD

**Issue by FailEnd** [jborean93/pypsrp#104]
hi,I want to use the command that "ps.add_cmdlet" to ban the e-mail address,but now it seems that I can use"-Confirm:$false"to realize it.

**Comment by jborean93** [comment]
You definitely can, a switch just acts like a boolean so you do `.add_parameter('Confirm', False)` or if you have a dict the key is the name (`Confirm`) and the value is `False`.
