### ISSUE TITLE
Missing requests-credssp dependency on install to support CredSSP auth

### ISSUE THREAD

**Issue by nodje** [jborean93/pypsrp#153]
ASAIU CredSSP is supported out of the box as a auth protocol for WSMAN.

But the requests-credssp isn't installed by default as a dep of pypsrp.

Shouldn't this be installed as expected?

**Comment by jborean93** [comment]
When requests-credssp was written it had a dependency on pyOpenSSL and cryptography and neither of those 2 packages had wheels. This meant to install them a user needed to have the Python headers and a valid compiler to compile the source code and that was never a guarantee. This is why it is an optional dependency that you can install with `pip install pypsrp[credssp]`.

Today the pyOpenSSL dependency has been dropped and cryptography has provided wheels for a lot of the platforms making it easier to install out of the box. In fact the upcoming pypsrp 1.0.0 release has dropped requests-credssp altogether in the new API making it work out of the box. But for now you will just have to ensure you install it using the extras syntax with pip.
