### ISSUE TITLE
Use pypsrp to access pep

### ISSUE THREAD

**Issue by thariman** [jborean93/pypsrp#17]
Hi is it possible to use pypsrp to do https://docs.microsoft.com/en-us/azure/azure-stack/azure-stack-privileged-endpoint

**Comment by jborean93** [comment]
@thariman sorry for the delay in the response, I seemed to have missed the notification. It should be possible as reading the docs indicate pep just uses JEA which pypsrp support. I don't know how to configure the actual server for this but if you've already done that it's just a matter of passing in the configuration name when creating the Runspace Pool when using the low level API. This can be done with

```
wsman = WSMan("hostname", ...)

with RunspacePool(wsman, configuration_name="PrivilegedEndpoint") as pool:
    ...
```

The value of `configuration_name` would correspond to the value you set on `-ConfigurationName` when using the `Enter-PSSession` cmdlet.  From there it's just a matter of calling whatever script/cmdlet that is allowed in that configuration just like normal.

**Comment by jborean93** [comment]
If you mean act as a server no. If you mean run over native WinRM/WinRS to a Windows host then yes.

**Comment by jborean93** [comment]
Closing as hopefully I've answered your question.
