### ISSUE TITLE
[Question] Kerberos stuff

### ISSUE THREAD

**Issue by XiaoliChan** [jborean93/pypsrp#180]
Hello jborean, I'm playing winrm with kerberos authentication, and I have a question: It's a way to set domain via variable when doing kerberos authentication?

![image](https://github.com/jborean93/pypsrp/assets/30458572/1d3ecbaa-35b5-45d2-b007-d180e29fc449)

code
```
Client(
                self.host,
                auth="kerberos",
                username=f"{domain}\\{self.username}",
                password=self.password,
                ssl=self.ssl,
                cert_validation=False,
            )
```

**Comment by XiaoliChan** [comment]
I have read the article for pypsrp, looks like it relate `klist` stuff

**Comment by jborean93** [comment]
On Linux you need to specify the domain using the UPN format `username@DOMAIN.COM`. In your example it would be `Client(username=f"{self.username}@{domain}")`.

**Comment by XiaoliChan** [comment]
> On Linux you need to specify the domain using the UPN format `username@DOMAIN.COM`. In your example it would be `Client(username=f"{self.username}@{domain}")`.

Thanks! now it recognize the domain from UPN, but any variable to set KDC host? (like `kdcHost` variable in impacket)
![image](https://github.com/jborean93/pypsrp/assets/30458572/3741271e-7b1b-466d-87b6-eff18dbdfeb2)

**Comment by jborean93** [comment]
There is none, it's up to your `krb5.conf` and how it is configured to lookup the KDC. This can either be hardcoded or it can be configured to lookup through DNS.

**Comment by XiaoliChan** [comment]
Got a new error
```
'SpnegoError (4294967295): Major (851968): Unspecified GSS failure.  Minor code may provide more information, Minor (2529638919): Server not found in Kerberos database, Context: Processing security token'
```

![image](https://github.com/jborean93/pypsrp/assets/30458572/a9467e38-f364-4081-a447-9ac2dc1db6bc)

**Comment by XiaoliChan** [comment]
Oh, same issue like https://github.com/jborean93/pyspnego/issues/55

**Comment by XiaoliChan** [comment]
@jborean93 Thank you for your help, now it works!

Code
```
self.conn = Client(
                self.host,
                auth="kerberos",
                #username=f"{self.domain}\\{self.username}",
                username=f"{self.username}@{self.domain.upper()}",
                password=self.password,
                ssl=self.ssl,
                cert_validation=False,
                negotiate_service='http',
                negotiate_hostname_override="dc-2019"
            )
```

![image](https://github.com/jborean93/pypsrp/assets/30458572/f8615140-4d75-4334-a035-e7ef90541d8c)

**Comment by XiaoliChan** [comment]
@jborean93 Sorry for ask this question again

I just noticed if I pass the password with nthash when doing Kerberos auth, it will be said my credential is invalid.
```
self.conn = Client(
                    self.host,
                    auth="kerberos",
                    username=f"{self.username}@{self.domain.upper()}",
                    password=f"00000000000000000000000000000000:{self.nthash}",
                    ssl=self.ssl,
                    cert_validation=False,
                    negotiate_service=spn,
                    negotiate_hostname_override=self.hostname,
                )
```

 so `pypsrp` only accept cleartext password when doing kerberos auth?

**Comment by jborean93** [comment]
Yes there is no support for providing a hash for Kerberos, you can provide the hash for NTLM though. You can use attempt to create a CCache for it to use but it cannot be provided through pypsrp. IIRC you cannot create Kerberos tokens directly from the hash unless you are using older enc types like RC4, AES is derived from a different key.

**Comment by XiaoliChan** [comment]
> Yes there is no support for providing a hash for Kerberos, you can provide the hash for NTLM though. You can use attempt to create a CCache for it to use but it cannot be provided through pypsrp. IIRC you cannot create Kerberos tokens directly from the hash unless you are using older enc types like RC4, AES is derived from a different key.

Fine, thanks for your reply!

Yes, just request a TGT instead of provide nthash is a solution!
