### ISSUE TITLE
Kerberos authentication error

### ISSUE THREAD

**Issue by adirn15** [jborean93/pypsrp#19]
the following code works on some remote hosts and fails on others, including failing on localhost:

1.    wsman = WSMan("hostname", auth="kerberos", cert_validation=False, ssl=False)
2.    with RunspacePool(wsman) as pool:
3.            *** more code here ***

it fails when with error:
pywintypes.error: (-2146893053, 'InitializeSecurityContext', 'The specified target is unknown or unreachable')

why does this happen? any help will be appreciated

**Comment by jborean93** [comment]
AFAIK that error occurs when the hostname you specify is not a valid hostname in the Kerberos/AD database. Usually for Kerberos you will use the fully qualified domain name for a host when connecting. In the case of SSPI the code https://github.com/jborean93/pypsrp/blob/master/pypsrp/spgnego.py#L225 will construct the SPN in the form of `<service>/<hostname>` where the defaults would be `WSMAN/hostname`. You can control the service and/or hostname with the `negotiate_hostname_override` and `negotiate_service` kwargs to WSMan.

This should theoretically allow you to do `wsman = WSMan("192.168.0.1", auth="kerberos", negotiate_hostname_override="host.domain.local")` to connect over an IP but use another hostname as part of the SPN.  I believe I did test the pywin32 side for this as I wrote the code but it's not something I can immediately test right now sorry.

**Comment by adirn15** [comment]
thank you for the quick reply, eventually i managed to resolve the issue using the default "negotiate" auth.
wsman = WSMan("hostname", auth="negotiate", cert_validation=False, ssl=False)

**Comment by jborean93** [comment]
That should work, just be careful as negotiate auth includes both kerberos and ntlm with the latter being used when kerberos is not.
