### ISSUE TITLE
The term 'Group-Object' is not recognized as the name of a cmdlet, function, script file, or operabl

### ISSUE THREAD

**Issue by SamGenTLEManKaka** [jborean93/pypsrp#29]
![image](https://user-images.githubusercontent.com/24671601/53478997-10632200-3ab3-11e9-9258-d8d2b01809cb.png)

![image](https://user-images.githubusercontent.com/24671601/53478885-d265fe00-3ab2-11e9-8fb5-2301e5099d62.png)

**Comment by SamGenTLEManKaka** [comment]
i will close this issues .
i think the problem happened elsewhere

**Comment by jborean93** [comment]
No worries, the error is returned by the server and not something generated in the Python library. It sounds like the `Microsoft.Exchange` endpoint has restricted a few cmdlets.
