### ISSUE TITLE
Powershell commands won't execute in Windows Server 2012 but works on Server 2016

### ISSUE THREAD

**Issue by avishka40** [jborean93/pypsrp#31]
I suppose this is because powershell core supports only windows server 2008 R2 ,2012 R2 and 2016 .

What platforms are supported?
PowerShell Core is officially supported on the following platforms:

Windows 7, 8.1, and 10
Windows Server 2008 R2, 2012 R2, 2016
Windows Server Semi-Annual Channel
Ubuntu 14.04, 16.04, and 17.04
Debian 8.7+, and 9
CentOS 7
Red Hat Enterprise Linux 7
OpenSUSE 42.2
Fedora 25, 26
macOS 10.12+

link: https://devblogs.microsoft.com/powershell/powershell-core-6-0-generally-available-ga-and-supported/
 
I tried both terminal commands which works fine and serveal non admin commands using powershell as well , powershell commands always ended up with empty process.stdout

**Comment by jborean93** [comment]
Are you able to share some more info, like the Python script you are running, the output of the script and so on. If PSCore supports 2008 R2 and 2012 R2, I see no reason why 2012 would be any different.

Also FYI, you don't need to use PowerShell Core with this library, by default it uses the PowerShell Desktop install but this is configurable.

**Comment by avishka40** [comment]
```python

class RemotePS(object):

    def __init__(self, server, auth, encryption, username, password, cert_validation):
        self.server = server
        self.auth = auth
        self.encryption = encryption
        self.username = username
        self.password = password
        self.cert_validation = cert_validation
        try:
            self.wsman = WSMan(server=self.server, ssl=False, auth=self.auth, encryption=self.encryption,
                               username=self.username, password=self.password, cert_validation=self.cert_validation)
            print "WinRS configured"
        except:
            print "WinRS config failed"

    def run_ps_cmd(self, cmdarray=[]):
        '''
        Wrapper run_cmd function only made to run power shell commands and return the output String
        Note that cmd needs to be passed as an argument array
        '''
        try:

            with WinRS(self.wsman) as shell:
                print 'Running Powershell cmd'
                # process = Process(shell, "dir")
                # output = process.invoke()
                # print process.stdout
                # process.signal(SignalCode.CTRL_C)

                # execute a process with arguments in the background
                process = Process(shell, "powershell", cmdarray)
                process.begin_invoke()  # start the invocation and return immediately
                output = process.poll_invoke()  # update the output stream
                process.end_invoke()  # finally wait until the process is finished
                print process.stdout
                process.signal(SignalCode.CTRL_C)

                return process.stdout
        except Exception, e:
            print str(e);
            return -1;
```

This is the sample code that I am using to run powershell commands, I forgot to inform you that I am trying to REMOTE CONNECT through winRm FROM Ubuntu 14.04 server to Windows Server(2016 and 2012), for 2016 server this works fine with no issues .

Sorry if the format is not clear.

**Comment by jborean93** [comment]
What's the issue, are you receiving an error, or traceback?

**Comment by avishka40** [comment]
I got no error or traceback, it was simply empty process.stdout , I don't have access to windows server 2012 right now , I will look in to it more  with in next few days , till then I will close the issue
Because I think I should be able to pin point something  late on

**Comment by jborean93** [comment]
Also as an FYI if all you are wanting to do it to execute a single process, you might be better off using the Client methods like so;

```
from pypsrp.client import Client

# Takes in the same kwargs as WSMan
client = Client(server=server, username=username, password=password)
stdout, stderr, rc = client.execute_cmd('dir')
```

This gives you the basic ability to run a command but becomes a lot more inefficient if you need to run multiple commands as each call to `execute_cmd` spawns a new shell whereas using the lower level API allows you to share the 1 shell.
