### ISSUE TITLE
Ability to pass environment variables and working directory to execute_cmd and execute_ps

### ISSUE THREAD

**Issue by nmaludy** [jborean93/pypsrp#33]
I've been looking at pypsrp as an alternative to pywinrm for various reasons.

One of the things i would love to see in pypsrp is a simple way to pass in environment variables and working directory into the `Client.execute_cmd` and `Client.execute_ps` functions. This reduces the burden on the end user having to know about all of the underlying details, creating shells, processes, etc.

Keep up the good work!

**Comment by jborean93** [comment]
Hi @nmaludy sorry for the delayed response, I've added this functionality in https://github.com/jborean93/pypsrp/pull/51. Feel free to test that out but it should be included in the next pypsrp release.
