### ISSUE TITLE
Received a WSManFault message. (Code: 2, Machine: XXX

### ISSUE THREAD

**Issue by santosshen** [jborean93/pypsrp#36]
`
try:
          wsman = WSMan(server='ip', username=username, password=password, ssl=True, cert_validation=False)
                            with RunspacePool(wsman) as pool:
                                ps = PowerShell(pool)
                                ps.add_script(r"Get-WmiObject -Class Win32_LogicalDisk")
                                output = ps.invoke()
                            if ps.had_errors:
                                print(ps.had_errors)
                        except Exception as e:
                            print(e)
`
![image](https://user-images.githubusercontent.com/25058112/58462115-cea25000-8163-11e9-9d45-f795e9b0630a.png)
__
Received a WSManFault message. (Code: 2, Machine: ip, Reason: WSMan The service was unable to start the host process to process the given request. Make sure that the host server and proxy for the WSMan provider are properly registered。)

![image](https://user-images.githubusercontent.com/25058112/58462032-98fd6700-8163-11e9-8c30-afc898b93384.png)

**Comment by jborean93** [comment]
It sounds like the actual PSRP dll is not registered property with WSMan on your Windows host. Are you able to connect with an actual PowerShell instance to your Windows host to rule it out?

**Comment by santosshen** [comment]
![image](https://user-images.githubusercontent.com/25058112/58525533-a3207380-81fe-11e9-95c1-26c9700e7928.png)

other services powershell  can  connect   Windows host

**Comment by santosshen** [comment]
Received a WSManFault message. (Code: 2147942402, Machine: ip, Reason: The system cannot find the file specified., Provider: Shell cmd plugin, Provider Path: %systemroot%\system32\winrscmd.dll, Provider Fault: System The specified file could not be found.)

%systemroot%\system32\winrscmd.dll

**Comment by jborean93** [comment]
@santosshen sorry I haven't gotten back to you earlier but were you able to find the issue/fix for this?

The `winrscmd.dll` is specific to WinRS and isn't really related to PowerShell remoting which the `Enter-PSSession` cmdlet tests out. It wouldn't make sense that the winrscmd.dll is being uses here though as the code you shared is PSRP specific.

I would be curious if you were able to run a command with [winrs](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/winrs). You should just be able to test it out like `winrs /r:http://<my_hostname> /u:<my_username> /p:<my_password> hostname`.

Some other good things to know would be;

* The Windows OS version you are connecting to
* The version of PowerShell that is installed on the host
* On what request does pypsrp fail, is it opening the runspace, pipeline, somewhere else?

**Comment by jborean93** [comment]
Closing as I cannot replicate and have received no more info on the issue. If you are still having this problem please reply and I'll reopen this.
