### ISSUE TITLE
how to add a powershell snapin

### ISSUE THREAD

**Issue by chinnaphani** [jborean93/pypsrp#38]
Hi,

How to add a powershell snapin and then execute a powershell command using pypsrp.

**Comment by jborean93** [comment]
If you are using `add_script` you would just add a line that has [Add-PSSnapin](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/add-pssnapin?view=powershell-5.1) like you do in a normal script. If you are using multiple statements and want it as an individual command you would do something like;

```
# By just using add_script
ps.add_script('''
Add-PSSnapin -Name My.Snapin
My-PSSnapinCmdlet -Param1 'Value 1' -Param2 'Value 2'
''')
ps.invoke()

# By using individual commands and statements
ps.add_cmdlet('Add-PSSnapin').add_parameter('Name', 'My.Snapin')
ps.add_statement()
ps.add_cmdlet('My-PSSnapinCmdlet').add_parameters({'Param1': "Value 1', 'Param2': 'Value 2'})
ps.invoke()
```

**Comment by chinnaphani** [comment]
Hi, 

Below is my code and its giving me error.

```from pypsrp.powershell import PowerShell, RunspacePool
from pypsrp.wsman import WSMan

wsman = WSMan("citrix.bluepedia.com",auth="ntlm",username="administrator",password="Vihaan@2016")

with RunspacePool(wsman) as pool:
    ps = PowerShell(pool)
    ps.add_cmdlet('Add-PSSnapin').add_parameter('Name','Citrix*')
    ps.add_statement()
    ps.add_cmdlet('Get-BrokerSite')
    ps.invoke()```

and the error is :

C:\Users\administrator\PycharmProjects\pstest\venv\Scripts\python.exe C:/Users/administrator/PycharmProjects/pstest/citrixps.py
Traceback (most recent call last):
  File "C:\Users\administrator\PycharmProjects\pstest\venv\lib\site-packages\urllib3\connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "C:\Users\administrator\PycharmProjects\pstest\venv\lib\site-packages\urllib3\connectionpool.py", line 344, in _make_request
    self._validate_conn(conn)
  File "C:\Users\administrator\PycharmProjects\pstest\venv\lib\site-packages\urllib3\connectionpool.py", line 843, in _validate_conn
    conn.connect()
  File "C:\Users\administrator\PycharmProjects\pstest\venv\lib\site-packages\urllib3\connection.py", line 370, in connect
    ssl_context=context)
  File "C:\Users\administrator\PycharmProjects\pstest\venv\lib\site-packages\urllib3\util\ssl_.py", line 355, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\administrator\AppData\Local\Programs\Python\Python37-32\lib\ssl.py", line 412, in wrap_socket
    session=session
  File "C:\Users\administrator\AppData\Local\Programs\Python\Python37-32\lib\ssl.py", line 853, in _create
    self.do_handshake()
  File "C:\Users\administrator\AppData\Local\Programs\Python\Python37-32\lib\ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\administrator\PycharmProjects\pstest\venv\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Users\administrator\PycharmProjects\pstest\venv\lib\site-packages\urllib3\connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\administrator\PycharmProjects\pstest\venv\lib\site-packages\urllib3\util\retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='citrix.bluepedia.com', port=5986): Max retries exceeded with url: /wsman (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)')))

During handling of the above exception, another exception occurred:

**Comment by jborean93** [comment]
This error is unrelated to the snappins and is around certificate validation of the your server. Please read through the [connection options](https://github.com/jborean93/pypsrp#connection) and more specifically the `cert_validation` option to control whether to validate the certificate or not. If you didn't want to use https then the `ssl` option can control that.

**Comment by chinnaphani** [comment]
Thank you friend, there is no error now, but i am getting this [ ] value when i use below code. plz help me i am new to python. 

and when i use the command in powershell this is output.

C:\Users\administrator> asnp citrix*
Get-BrokerSite |Select-Object Name

Name        
----        
mycitrixfarm



```from pypsrp.powershell import PowerShell, RunspacePool
from pypsrp.wsman import WSMan

wsman = WSMan("citrix.bluepedia.com",auth="ntlm",username="administrator",password="Vihaan@2016",cert_validation=False,ssl=False)

with RunspacePool(wsman) as pool:
    ps = PowerShell(pool)
    ps.add_cmdlet('Add-PSSnapin').add_parameter('Name','Citrix*')
    ps.add_statement()
    ps.add_cmdlet('Get-BrokerSite').add_cmdlet('Select-Object').add_parameter('Name')
    ps.invoke()
    out = ps.output
    print(out)```

**Comment by jborean93** [comment]
I highly recommend you use the `execute_ps` method in `client.py` https://github.com/jborean93/pypsrp/blob/master/pypsrp/client.py#L203. You just pass in the script as a string and it will automatically try and convert the output to a string and not a managed object for you. You can continue to go ahead with the low level API if you wish but unless you are dealing with simple object or can debug it interactively you will probably not progress much further.

**Comment by chinnaphani** [comment]
hey thank you, i tried the below command it really works, and it gives below out out, but i just want to remove Name and -------

Name                                                                                                                    
----                                                                                                                    
CitrixXDSalem

```
with RunspacePool(wsman) as pool:
    ps = PowerShell(pool)
    # ps.add_script()
    ps.add_cmdlet('Add-PSSnapin').add_parameter('Name', 'Citrix*')
    ps.add_statement()
    ps.add_cmdlet("Invoke-Expression").add_parameter("Command", "Get-BrokerSite |Select Name")
    ps.add_cmdlet("Out-String").add_parameter("Stream")
    ps.invoke()
    print("\n".join(ps.output))```

**Comment by chinnaphani** [comment]
Hi, Thank you again, i managed with one last question, how can i run second command in same loop.

for example, i want to run command "Get-BrokerMachine"


```print("\n".join(ps.output[3:]))```

**Comment by jborean93** [comment]
Do what you would normally do in powershell

```
# Put as many commands you want here
script = '''
(Get-BrokerSite).Name
Get-BrokerMachine
'''

ps.add_cmdlet('Invoke-Expression').add_parameter('Command', script)
ps.add_cmdlet('Out-String').add_parameter('Stream')
ps.invoke()
```

**Comment by chinnaphani** [comment]
It works, but i want to store the result of each command to a variable for example and display them in a html using django. 

if i give all command in script as your specified, its printing as plain text.

for example : sitename = get.brokersite.Name
                     MachineName = get-brokerMachine.Name

**Comment by jborean93** [comment]
You can still do that you just need to split by newline as each output will be put onto a new line in `ps.output`.

**Comment by chinnaphani** [comment]
Hi friend,

Sorry for troubling you, i am trying hard for code case for running another powershell command , as specified i can run multiple command if i use script = '' but i wan to add the result to a variable, below is my example and i want to add value2 = "Get-BrokerSite |Select LocalHostCacheEnabled", can you plz send me a use case code. 

Also the code works for get powershell command, i have powershell command "New-BrokerMachine -CatalogUid 2 -MachineName 'bluepedia\testvda002" this command works in powershell console but not really from below code.

plz help by sending a usage code .

```from pypsrp.powershell import PowerShell, RunspacePool
from pypsrp.wsman import WSMan

wsman = WSMan("citrix.bluepedia.com",auth="ntlm",username="administrator",password="Vihaan@2016",cert_validation=False,ssl=False)

script = ''''
New-BrokerMachine -CatalogUid 2 -MachineName 'bluepedia\testvda002'
'''''

with RunspacePool(wsman) as pool:
    ps = PowerShell(pool)
    # ps.add_script()
    ps.add_cmdlet('Add-PSSnapin').add_parameter('Name', 'Citrix*')
    ps.add_statement()
    ps.add_cmdlet("Invoke-Expression").add_parameter("Command", "Get-BrokerSite |Select Name")
    # ps.add_cmdlet("Invoke-Expression").add_parameter("Command", "Get-BokerSite")
    # ps.add_cmdlet("Invoke-Expression").add_parameter("Command", "Get-BrokerSite")
    # ps.add_cmdlet("New-BrokerMachine -CatalogUid 2 -MachineName 'bluepedia\testvda002")

    ps.add_cmdlet("Out-String").add_parameter("Stream")
    ps.invoke()
    value1 = "\n".join(ps.output[3:])
    print(value1)```

**Comment by chinnaphani** [comment]
can you plz help on above question

**Comment by jborean93** [comment]
> i am trying hard for code case for running another powershell command , as specified i can run multiple command if i use script = '' but i wan to add the result to a variable

There are multiple ways to do this, the easiest way is to just output a string then parse the output stream (`ps.output`). This parsing is dependent on how you actually output the value. Honestly I can't help you with this as it's up to you to run whatever script you want and then parse the output.

> Also the code works for get powershell command, i have powershell command "New-BrokerMachine -CatalogUid 2 -MachineName 'bluepedia\testvda002" this command works in powershell console but not really from below code.

You need to look at the error stream in the ps object to see what the error was. Having a brief look you are not escaping `\` in `-MachineName` so the value becomes `bluepedia<tab>estvda002`. You want to escape the `\` like `\\` or prefix the entire string with `r`. This is a Python thing and not something unique to pypsrp.

It looks like your issue not an actual problem with pypsrp but just how to run the scripts and look at the output. You've got the basics in there but you just need to connect the dots. There's not too much I can do from here so I'm going to close this issue.
