### ISSUE TITLE
TypeError: 'NoneType' object is not iterable in serializer.py

### ISSUE THREAD

**Issue by gordonj7** [jborean93/pypsrp#4]
In serializer.py:

```
class Serializer(object):
...
    def _deserialize_lst(self, element, metadata=None):
        list_value = []
        value_meta = getattr(metadata, "list_value_meta", None)

        entries = element.find("LST")
        for entry in entries:
            entry_value = self.deserialize(entry, value_meta, clear=False)
            list_value.append(entry_value)

        return list_value
```

In some cases, `entries` is None, and thus the `for` throws an exception.

I fixed this locally by adding these two lines above the loop:

```
        if entries is None:
            return list_value
```

**Comment by jborean93** [comment]
Hmm, sounds more like a bug with the code that determines what `_deserialize_*` method to call. Do you have an example code to produce this error now?

**Comment by gordonj7** [comment]
I didn't document the exact conditions under which this bug occurred, and now I'm having trouble reproducing it.  Hopefully I will have a reply soon.

**Comment by gordonj7** [comment]
I am able to reproduce.
[issue4.log](https://github.com/jborean93/pypsrp/files/2354703/issue4.log)

**Comment by jborean93** [comment]
Fantastic, will make a release sometime shortly with the changes and will close this issue once that's done.

**Comment by jborean93** [comment]
@gordonj7 a new release at `0.2.0` has been created https://github.com/jborean93/pypsrp/releases/tag/v0.2.0. Closing this issue.
