### ISSUE TITLE
cannot execute EMS scripts

### ISSUE THREAD

**Issue by qxrftz** [jborean93/pypsrp#41]
The following command can be executed successfully on local powershell:
```
Add-PSsnapin Microsoft.Exchange.Management.PowerShell.E2010
New-Mailbox -UserPrincipalName "test@test.com" -Name "test" -SamAccountName "test"
```
but it cannot be executed via pypsrp.

> Possible reason
<https://blogs.technet.microsoft.com/samdrey/2015/04/06/reminder-adding-exchange-2010-or-2013-snap-in-using-add-pssnapin-not-supported-better-use-remote-powershell-from-rmilne/>

**Comment by jborean93** [comment]
I'm not sure what is happening, are you getting an error? Can you share that? pypsrp supports different configuration names as the endpoint to connect to which is set by the `configuration_name` kwarg when creating the RunspacePool object.

**Comment by qxrftz** [comment]
pypsrp.exceptions.WSManFaultError: Received a WSManFault message. (Code: 2150858811, Machine: 1.1.1.1, Reason: The WS-Management service cannot process the request. The resource URI (http://schemas.microsoft.com/powershell/Microsoft.Exchange) was not found in the WS-Management catalog.

**Comment by qxrftz** [comment]
> pypsrp.exceptions.WSManFaultError: Received a WSManFault message. (Code: 2150858811, Machine: 1.1.1.1, Reason: The WS-Management service cannot process the request. The resource URI (http://schemas.microsoft.com/powershell/Microsoft.Exchange) was not found in the WS-Management catalog.

This error has been fixed by registering powershell sessions plugin.
```
Register-PSSessionConfiguration -name Microsoft.Exchange -StartupScript "C:\Import_EMS.ps1" -RunAsCredential $EMSApiCredential
```
Then I can execute EMS via WinRM on my local powershell now, but still cannot do it via pypsrp, the following error msg is for your reference.
```
Traceback (most recent call last):
  File ".pyenv/versions/test/test/utilities/powershell.py", line 8, in <module>
    with RunspacePool(wsman, configuration_name='Microsoft.Exchange') as pool:
  File ".pyenv/versions/test/lib/python3.6/site-packages/pypsrp/powershell.py", line 198, in __enter__
    self.open()
  File ".pyenv/versions/test/lib/python3.6/site-packages/pypsrp/powershell.py", line 511, in open
    responses.extend(self._receive())
  File ".pyenv/versions/test/lib/python3.6/site-packages/pypsrp/powershell.py", line 635, in _receive
    return self._parse_responses(response, pipeline)
  File ".pyenv/versions/test/lib/python3.6/site-packages/pypsrp/powershell.py", line 679, in _parse_responses
    response_function = response_functions[message.message_type]
KeyError: 266246

Process finished with exit code 1
```

**Comment by qxrftz** [comment]
> > pypsrp.exceptions.WSManFaultError: Received a WSManFault message. (Code: 2150858811, Machine: 1.1.1.1, Reason: The WS-Management service cannot process the request. The resource URI (http://schemas.microsoft.com/powershell/Microsoft.Exchange) was not found in the WS-Management catalog.
> 
> This error has been fixed by registering powershell sessions plugin.
> 
> ```
> Register-PSSessionConfiguration -name Microsoft.Exchange -StartupScript "C:\Import_EMS.ps1" -RunAsCredential $EMSApiCredential
> ```
> 
> Then I can execute EMS via WinRM on my local powershell now, but still cannot do it via pypsrp, the following error msg is for your reference.
> 
> ```
> Traceback (most recent call last):
>   File ".pyenv/versions/test/test/utilities/powershell.py", line 8, in <module>
>     with RunspacePool(wsman, configuration_name='Microsoft.Exchange') as pool:
>   File ".pyenv/versions/test/lib/python3.6/site-packages/pypsrp/powershell.py", line 198, in __enter__
>     self.open()
>   File ".pyenv/versions/test/lib/python3.6/site-packages/pypsrp/powershell.py", line 511, in open
>     responses.extend(self._receive())
>   File ".pyenv/versions/test/lib/python3.6/site-packages/pypsrp/powershell.py", line 635, in _receive
>     return self._parse_responses(response, pipeline)
>   File ".pyenv/versions/test/lib/python3.6/site-packages/pypsrp/powershell.py", line 679, in _parse_responses
>     response_function = response_functions[message.message_type]
> KeyError: 266246
> 
> Process finished with exit code 1
> ```

This error has been fixed by changing powershell session configuration.
```
Register-PSSessionConfiguration -name Microsoft.Exchange ~~-StartupScript "C:\Import_EMS.ps1"~~ -RunAsCredential $EMSApiCredential
```
Then the following code works:
```python
from pypsrp.complex_objects import ObjectMeta
from pypsrp.powershell import PowerShell, RunspacePool
from pypsrp.wsman import WSMan


if __name__ == '__main__':
    wsman = WSMan('1.1.1.1', username='api_ems@test.com', password='abc123', cert_validation=False)
    with RunspacePool(wsman, configuration_name='Microsoft.Exchange') as pool:
        pool.exchange_keys()
        ps = PowerShell(pool)
        ps.add_cmdlet('Add-PSSnapin').add_argument('Microsoft.Exchange.Management.PowerShell.SnapIn')
        ps.add_statement()
        ps.add_cmdlet('New-Mailbox').add_parameters({
            'OrganizationalUnit': 'test.com/Users',
            'UserPrincipalName': 'test1@test.com',
            'Name': 'test1(test)',
            'SamAccountName': 'test1',
            'DisplayName': 'test1(test)',
            'LastName': 'test1(test)',
            'Password': pool.serialize('xxx.yyy', ObjectMeta('SS')),
            'ResetPasswordOnNextLogon': pool.serialize(True, ObjectMeta('B')),
        })
        ps.add_cmdlet('Out-String').add_parameter('Stream')
        ps.add_statement()
        ps.add_cmdlet('New-Mailbox').add_parameters({
            'OrganizationalUnit': 'test.com/Users',
            'UserPrincipalName': 'test2@test.com',
            'Name': 'test2(test)',
            'SamAccountName': 'test2',
            'DisplayName': 'test2(test)',
            'LastName': 'test2(test)',
            'Password': pool.serialize('xxx.yyy', ObjectMeta('SS')),
            'ResetPasswordOnNextLogon': pool.serialize(True, ObjectMeta('B')),
        })
        ps.add_cmdlet('Out-String').add_parameter('Stream')
        ps.invoke()
``
