### ISSUE TITLE
Unable to access network drive Z:

### ISSUE THREAD

**Issue by santosshen** [jborean93/pypsrp#42]
hi jborean93:
```
wsman = WSMan(server=ip, username=username, password=password, ssl=True, cert_validation=False)
                with RunspacePool(wsman) as pool:
                    ps = PowerShell(pool)
                    ps.add_script(r'dir z:')
                    output = ps.invoke()
```

Unable to access network drive Z:

![image](https://user-images.githubusercontent.com/25058112/62856853-9523be80-bd28-11e9-90a5-12c3018acc33.png)

**Comment by santosshen** [comment]
```
from pypsrp.client import Client

# Takes in the same kwargs as WSMan
client = Client(server=server, username=USERNAME, password=PASSWORD,ssl=False, cert_validation=False,)
stdout, stderr, rc = client.execute_cmd('dir Z:')
# stderr = stderr.decode(encoding='gbk')
print(stderr)

```

stderr :  The system cannot find the specified path

**Comment by jborean93** [comment]
This is as expected, you cannot access network drives in a network logon like WinRM. This isn't limited to this library but anything that relies on a network logon like WinRM, PsExec and so on.

I've gone into detail about how mapped drives actually work with https://www.bloggingforlogging.com/2018/11/22/windows-mapped-drives-what-the-hell-is-going-on/. Your best bet is to use a UNC path to reference the network location but you also need to take into consideration the [double-hop/credential delegation](https://blogs.technet.microsoft.com/ashleymcglone/2016/08/30/powershell-remoting-kerberos-double-hop-solved-securely/) issue when it comes to WinRM. This library supports both Kerberos delegation as well as CredSSP so it is possible to access a network location using the UNC path.

**Comment by santosshen** [comment]
thanks
