### ISSUE TITLE
Cant invoke multiple commands

### ISSUE THREAD

**Issue by Rohith050** [jborean93/pypsrp#56]
Hi, Tried running RunspacePool/PowerShell example given in the  Readme.md. Ran into the below error

> Traceback (most recent call last):
>   File ".\website.py", line 17, in <module>
>     ps.begin_invoke()  # execute process in the background
>   File "C:\Users\xxxxxxx\AppData\Local\Programs\Python\Python37\lib\site-packages\pypsrp\powershell.py", line 1009, in begin_invoke
>     "start a PowerShell pipeline"
> pypsrp.exceptions.InvalidPipelineStateError: Cannot 'start a PowerShell pipeline' on the current state 'Completed', expecting state(s): 'NotStarted'

I have used the example as it is except for the authentication method. 
```
from pypsrp.powershell import PowerShell, RunspacePool
from pypsrp.wsman import WSMan

# creates a https connection with explicit kerberos auth and implicit credentials
wsman = WSMan("1.1.1.1", ssl=False, auth="basic", encryption="never",
              username="xxxx", password="xxxx")

with RunspacePool(wsman) as pool:
    # execute 'Get-Process | Select-Object Name'
    ps = PowerShell(pool)
    ps.add_cmdlet("Get-Process").add_cmdlet("Select-Object").add_argument("Name")
    output = ps.invoke()

    # execute 'Get-Process | Select-Object -Property Name'
    ps.add_cmdlet("Get-Process").add_cmdlet("Select-Object")
    ps.add_parameter("Property", "Name")
    ps.begin_invoke()  # execute process in the background
    ps.poll_invoke()  # update the output streams
    ps.end_invoke()  # wait until the process is finished

    # execute 'Get-Process | Select-Object -Property Name; Get-Service audiosrv'
    ps.add_cmdlet("Get-Process").add_cmdlet("Select-Object").add_parameter("Property", "Name")
    ps.add_statement()
    ps.add_cmdlet("Get-Service").add_argument("audiosrc")
    ps.invoke()

    # execute a PowerShell script with input being sent
    script = '''begin {
    $DebugPreference = "Continue"
    Write-Debug -Message "begin"
} process {
    Write-Output -InputObject $input
} end {
    Write-Debug -Message "end"
}
'''
    ps.add_script(script)
    ps.invoke(["string", 1])
    print(ps.output)
    print(ps.streams.debug)
```
First command invoke is successful, failed while invoking the second one.
I have started using pypsrp just today. Am i missing something basic here?
Python: 3.7.4
Remote windows: Windows server 2016

Thanks in advance for the help.

**Comment by jborean93** [comment]
AFAIK you cannot invoke a pipeline multiple times and it's a 1 invoke per pipeline. The example I have should probably be updated but you just need to set `ps` back to `PowerShell(pool)` when you want to start a new pipeline. It should probably be under a different var name as well to ensure you don't loose any output.

If you are wanting to invoke multiple commands or scripts in the 1 pipeline (in the 1 invoke) you will need to separate them as statements, e.g.

```
# This is the same as 'Get-Process -Id 1 | Stop-Process' as there is no statement in between the cmdlets
ps = PowerShell(pool)
ps.add_cmdlet("Get-Process").add_parameter("Id", 1)
ps.add_cmdlet("Stop-Process")
ps.invoke()

# This is the same as 'Get-Process -Id 1; Stop-Process -Id 1' as we put a statement in between
ps = PowerShell(pool)
ps.add_cmdlet("Get-Process").add_parameter("Id", 1)
ps.add_statement()  # Basically adds the ';' or newline to separate commands
ps.add_cmdlet("Stop-Process").add_parameter("Id", 1)
ps.invoke()
```

Hopefully that helps to explain how it works, ultimately the `PowerShell` object is to closely reflect the actual [PowerShell .NET class](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.powershell?view=pscore-6.2.0) with a few slight changes.
