### ISSUE TITLE
Access to a CIM resource was not available to the client

### ISSUE THREAD

**Issue by neoluu** [jborean93/pypsrp#57]
Im using python on linux and trying to execute cmdlets on a remote window 2008/2012/2016 server. The windows domain account im using is part of an AD group that is a member of the server local Administrators group. Login on to the server with the account works and im able to do what i want.

But from my linux server via the python command, Im unable to use New-DfsnFolderTarget cmdlet. I get error "Access to a CIM resource was not available to the client". I believe this could be one of those double-hop commands. Can you advise how I can get around/correct this or what im doing wrong?

**Comment by jborean93** [comment]
If it’s trying to access a resource on another host then it is definitely a double hop issue. You can either

* Set `auth=‘credssp’`
* Set `auth=‘kerberos’` with `negotiate_delegation=True`
* Set explicit credentials if supported by the cmdlet
* Use some other mechanism like a scheduled task or psexec spawned by pypsrp
