### ISSUE TITLE
Consider adding option to supply custom HTTPAdapter

### ISSUE THREAD

**Issue by ecbftw** [jborean93/pypsrp#60]
I'd like to be able to control a lot more about how my client validates HTTPS certificates and other low level communications options.  pypsrp uses requests, which is fine, and apparently the way you control these things in requests is to subclass `HTTPAdapter` and muck around with the SSL context and other settings.  Then you use the `mount()` method on a requests session to make it take effect.

In order to support this, we'd need to be able to specify our own custom HTTPAdapter class as some kind of argument (I'm guessing) and then you'd want to make sure all requests generated by pypsrp use the session/mount paradigm with that adapter.  (I see you're already using an adapter like this in one place, but not in all.)

Thoughts?

**Comment by ecbftw** [comment]
I was able to monkey patch around this limitation by doing:
```
wsman = WSMan(...)
wsman.transport.session = wsman.transport._build_session()
wsman.transport.session.mount('https://', MyCustomAdapter())
```

That obviously runs the risk of breaking when internals of pypsrp change.  Since `**kwargs` are passed on to the `_TransportHTTP` constructor, what if we just have that constructor store any  `custom_adapter` argument as an attribute on the object, and then when _build_session runs, use that adapter (if set) instead of the default one?

**Comment by jborean93** [comment]
I would be very wary of actually doing this, I personally don't want to try and expose a requests interface in the pypsrp transport in case the library ever wants to drop requests for something else. What would be better is to expose the cert validation logic through some other simple kwarg, i.e. having `cert_validation` take in a string (as well as bool for backwards compat) that state the validation you want. Then finally implement that logic internally against requests. I see this as a better way because

* People who want to take advantage of the logic you have no longer have to implement it themselves, it's just a simple kwarg string to set
* If we move away from requests we no longer have a breaking change where user's pass in an "opaque" object which we relied on requests to handle

**Comment by ecbftw** [comment]
Ok, I understand the desire to avoid expose inner workings.  However, a simple string or other option argument just wont' be flexible enough for anything beyond very simple validation logic.

What I have implemented is a way to handle certificate validation in a multi-tiered way, starting off with the traditional CA-based validation system, followed by an optional trust-on-first-use (TOFU) system.  The TOFU logic is complex, but extremely helpful for the end user in my application.  (Imagine trying to run scripts on thousands of system that have self-signed certs... TOFU can make that reasonably secure without having to reconfigure every service with CA-signed certs.)

Some people might have some dogmatic tendencies and take issue with the specific validation I want to perform, but suffice it to say, some developers like me have reasonable motivations to want *much* more flexibility out of their certificate validation routines and to define policies that you'd never want to include as an explicit option in pypsrp.

How about this as a middle ground?  Allow the caller to provide a callback function as an argument.  Their callback function would performs validation of certificates and return True/False accordingly.  That would give me the flexibility I need without locking you in to using requests. What would the interface to that callback function be?  A starting point to consider would be the `callback` argument of this:
  https://www.pyopenssl.org/en/stable/api/ssl.html#OpenSSL.SSL.Context.set_verify

How would you go about exposing this kind of interface? It is maybe not trivial, but perhaps I could help.  Note that only pyOpenSSL has something like this (the built-in ssl library still doesn't, but requests/urllib3 have support to force usage of pyOpenSSL).  Yes, I realize this may lock you in to using pyOpenSSL, but that is a much lower-level library and one of only two practical ways to do TLS in Python.

**Comment by jborean93** [comment]
A callback function is a good idea and I'm ok with adding something like that, the trouble I am seeing is how to safely get that certificate information in the callback as you indicated. From reading it doesn't seem like requests gives you access to the connection socket it uses and requires either monkeypatching or accessing private functions/properties which is not something I would really support.

You could use pyOpenSSL to create a new connection and get the certificate there, the same applies for just using `socket` but even then that's not part of the actual connection being made that will have the data transferred over. For me to be ok with including something like this in the library it would have to

* Not be reliant on passing requests specific objects into WSMan, e.g. all the requests specific code would have to be in WSMan itself
* Optional, i.e. I don't want to force people to have pyOpenSSL installed or some other 3rd party library
* The verification is made on the connection that is being made, not some extra connection used for verification
    * The end user can just do this themselves

**Comment by ecbftw** [comment]
Yes, these are all legit concerns.  

I'd be happy to create my own pyOpenSSL connection and hand the socket off to pypsrp, but as you have noticed, requests/urllib3 has no ability to pass a socket in and despite multiple tickets related to that, the authors don't want to add that capability because they have a complex connection pool internally.  Creating a socket and testing the certificate only to turn around and use a different connection for the actual data... as you pointed out, that would result in a security vulnerability due to the race so it's a nonstarter.

I'm starting to wonder if requests/urllib3 just isn't an appropriate library for this kind of usage.  They've made it to be super developer-friendly for the 95% of cases that most people deal with.  While I like the library, the development goals are at odds with advanced usage for non-web scenarios.  One option (and I realize this is a huge ask) is to ditch requests sooner rather than later and then allow callers to pass in a socket.

It may also be possible to come up with a hybrid solution that overrides the urllib3 connection pool with a subclass that allows a socket to be passed in.  The requests/urllib3 folks regularly recommend to users (in their tickets) that developers can subclass connection pool related classes and use those instead.  If that works, it might be the easiest and cleanest path forward.

Another option would be to allow callers to pass in a simple non-requests-specific callback function, and when that happens, do a check to ensure pyOpenSSL is available.  If it is, then do the hacks necessary (e.g. what I've been doing) to make the callback work with requests.  The callback argument could have documentation tied to it that it requires pyOpenSSL.  Any usage without the callback would allow the native python ssl module.  Not pretty, but it would work.

**Comment by jborean93** [comment]
It really does sound like it's the barrier to what you want to achieve and I don't see an easy way of implementing this without locking you in place.

> It may also be possible to come up with a hybrid solution that overrides the urllib3 connection pool with a subclass that allows a socket to be passed in. 

I think this is the only sane way forward but moving away from requests won't be an easy task. The biggest issue is around authentication and while the code for auth for NTLM and Kerberos are in this library we use [requests-credssp](https://github.com/jborean93/requests-credssp) for CredSSP auth. This is currently geared towards a requests model and would have to be modified or have certain components stripped out to enable urllib3 support.

It would be nice to drop the requests support and use something builtin to Python but there's a lot of work involved to get there.

> Another option would be to allow callers to pass in a simple non-requests-specific callback function

This sounds like the "simplest" option to implement what you want but even then I don't know how you will get the certificate info on an active connection without using some private methods. I'm fine with checking if pyOpenSSL is available for this functionality but I wouldn't want to rely on private methods or monkeypatching of requests as we could get into a version hell if we target a subset of requests versions.

**Comment by ecbftw** [comment]
I'll try to look into the connection pool idea when I find time and report back.

**Comment by graingert** [comment]
> I was able to monkey patch around this limitation by doing:
> 
> ```
> wsman = WSMan(...)
> wsman.transport.session = wsman.transport._build_session()
> wsman.transport.session.mount('https://', MyCustomAdapter())
> ```
> 
> That obviously runs the risk of breaking when internals of pypsrp change. Since `**kwargs` are passed on to the `_TransportHTTP` constructor, what if we just have that constructor store any `custom_adapter` argument as an attribute on the object, and then when `_build_session` runs, use that adapter (if set) instead of the default one?

I've found it a bit nicer to subclass the client:

```python
class _WSMan(pypsrp.wsman.WSMan):
    def _build_session(self, *args, **kwargs):
        session = super()._build_session(*args, **kwargs)
        session.mount("https://", MyCustomAdapter())
        return session


class _PSRPClient(pypsrp.client.Client):
    def __init__(self, server, **kwargs):
        self.wsman = _WSMan(server, **kwargs)
```

**Comment by jborean93** [comment]
While not implemented by the `pypsrp` namespace you can now create a WSMan based connection with a custom SSL context defined in Python with the new `psrp` stuff coming out in the v1.0.0 release.

```python
import psrp

def main():
    ssl_context = ssl.create_default_context()
    # Adjust however you wish

    conn = psrp.WSManInfo('server', ssl_context=ssl_context)
    with psrp.SyncRunspacePool(conn) as rp:
        ...
```
