### ISSUE TITLE
How to reconnect an existing powershell session?

### ISSUE THREAD

**Issue by AndrewTsao** [jborean93/pypsrp#62]
Hi, I started a long service process through pypsrp remote shell. I update config as follow.

```powershell
Set-Item WSMan:\localhost\Shell\IdleTimeout 2147483647
```
2147483647 is the maximum of IdleTimeout. After about 24 days, the shell and subprocesses were killed by OS because shell idle timeout.

Can I reconnect existing shell, and execute some command to avoid timeout?

**Comment by jborean93** [comment]
I don't think you can through WinRM itself, that `IdleTimeout` corresponds to the [IdleTimeoutms](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-wsmv/7ffb4acd-cf01-4fbe-9e48-7746f5001957) quota option documented in the MS-WSMV protocol. It states that this value is

> An optional value that specifies an idle time-out for Shells created by this particular plug-in. The value MUST be expressed in milliseconds. The minimum value MUST be 60000. The maximum value MUST be 2147483647. The default value SHOULD be 180000. The service SHOULD close and terminate the shell instance if it is idle for this amount of time. If the Shell is reused within this time limit, the countdown timer is reset once the command sequence is completed.

There's no talk of an infinite value so I think you are at the mercy of WSMan here. In any case if you have something that is as long running as this then you are better off creating it as a Windows service or scheduled task and using pypsrp to interact with that process through some other means.

**Comment by jborean93** [comment]
Closing as per the above.
