### ISSUE TITLE
kerberos auth fails with psrp while working with winrm

### ISSUE THREAD

**Issue by willofr** [jborean93/pypsrp#65]
Hi !

i'm trying to authenticate windows servers with pypsrp with Ansible. While it's working perfectly fine with Winrm module, it fails with psrp with error __"Server not found in Kerberos database"__.

**inventory used:**
[windows]
dc.whcorp.lan

[windows:vars]
ansible_user=ansible_svc@WHCORP.LAN
ansible_ssh_pass=********
ansible_connection=psrp
#ansible_connection=winrm
ansible_port=5985
ansible_psrp_auth=kerberos

__Output with winrm module:__

will@ansible:~$ ansible -vvvvv windows -m win_ping
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/will/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.3 (default, Dec 20 2019, 18:57:59) [GCC 8.3.0]
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
auto declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Parsed /etc/ansible/hosts inventory source with ini plugin
Loading callback plugin minimal of type stdout, v2.0 from /usr/local/lib/python3.7/dist-packages/ansible/plugins/callback/minimal.py
META: ran handlers
Using module file /usr/local/lib/python3.7/dist-packages/ansible/modules/windows/win_ping.ps1
Pipelining is enabled.
<dc.whcorp.lan> ESTABLISH WINRM CONNECTION FOR USER: ansible_svc@WHCORP.LAN on PORT 5985 TO dc.whcorp.lan
__creating Kerberos CC at /tmp/tmpc79b4e09
calling kinit with subprocess for principal ansible_svc@WHCORP.LAN
kinit succeeded for principal ansible_svc@WHCORP.LAN
<dc.whcorp.lan> WINRM CONNECT: transport=kerberos endpoint=http://dc.whcorp.lan:5985/wsman__
<dc.whcorp.lan> WINRM OPEN SHELL: 9C788938-97F0-4AC5-9B04-0F9981962A89
EXEC (via pipeline wrapper)
<dc.whcorp.lan> WINRM EXEC 'PowerShell' ['-NoProfile', '-NonInteractive', '-ExecutionPolicy', 'Unrestricted', '-EncodedCommand', 'UABvAHcAZQByAFMAaABlAGwAbAAgAC0ATgBvAFAAcgBvAGYAaQBsAGUAIAAtAE4AbwBuAEkAbgB0AGUAcgBhAGMAdABpAHYAZQAgAC0ARQB4AGUAYwB1AHQAaQBvAG4AUABvAGwAaQBjAHkAIABVAG4AcgBlAHMAdAByAGkAYwB0AGUAZAAgAC0ARQBuAGMAbwBkAGUAZABDAG8AbQBtAGEAbgBkACAASgBnAEIAagBBAEcAZwBBAFkAdwBCAHcAQQBDADQAQQBZAHcAQgB2AEEARwAwAEEASQBBAEEAMgBBAEQAVQBBAE0AQQBBAHcAQQBEAEUAQQBJAEEAQQArAEEAQwBBAEEASgBBAEIAdQBBAEgAVQBBAGIAQQBCAHMAQQBBAG8AQQBKAEEAQgBsAEEASABnAEEAWgBRAEIAagBBAEYAOABBAGQAdwBCAHkAQQBHAEUAQQBjAEEAQgB3AEEARwBVAEEAYwBnAEIAZgBBAEgATQBBAGQAQQBCAHkAQQBDAEEAQQBQAFEAQQBnAEEAQwBRAEEAYQBRAEIAdQBBAEgAQQBBAGQAUQBCADAAQQBDAEEAQQBmAEEAQQBnAEEARQA4AEEAZABRAEIAMABBAEMAMABBAFUAdwBCADAAQQBIAEkAQQBhAFEAQgB1AEEARwBjAEEAQwBnAEEAawBBAEgATQBBAGMAQQBCAHMAQQBHAGsAQQBkAEEAQgBmAEEASABBAEEAWQBRAEIAeQBBAEgAUQBBAGMAdwBBAGcAQQBEADAAQQBJAEEAQQBrAEEARwBVAEEAZQBBAEIAbABBAEcATQBBAFgAdwBCADMAQQBIAEkAQQBZAFEAQgB3AEEASABBAEEAWgBRAEIAeQBBAEYAOABBAGMAdwBCADAAQQBIAEkAQQBMAGcAQgBUAEEASABBAEEAYgBBAEIAcABBAEgAUQBBAEsAQQBCAEEAQQBDAGcAQQBJAGcAQgBnAEEARABBAEEAWQBBAEEAdwBBAEcAQQBBAE0AQQBCAGcAQQBEAEEAQQBJAGcAQQBwAEEAQwB3AEEASQBBAEEAeQBBAEMAdwBBAEkAQQBCAGIAQQBGAE0AQQBkAEEAQgB5AEEARwBrAEEAYgBnAEIAbgBBAEYATQBBAGMAQQBCAHMAQQBHAGsAQQBkAEEAQgBQAEEASABBAEEAZABBAEIAcABBAEcAOABBAGIAZwBCAHoAQQBGADAAQQBPAGcAQQA2AEEARgBJAEEAWgBRAEIAdABBAEcAOABBAGQAZwBCAGwAQQBFAFUAQQBiAFEAQgB3AEEASABRAEEAZQBRAEIARgBBAEcANABBAGQAQQBCAHkAQQBHAGsAQQBaAFEAQgB6AEEAQwBrAEEAQwBnAEIASgBBAEcAWQBBAEkAQQBBAG8AQQBDADAAQQBiAGcAQgB2AEEASABRAEEASQBBAEEAawBBAEgATQBBAGMAQQBCAHMAQQBHAGsAQQBkAEEAQgBmAEEASABBAEEAWQBRAEIAeQBBAEgAUQBBAGMAdwBBAHUAQQBFAHcAQQBaAFEAQgB1AEEARwBjAEEAZABBAEIAbwBBAEMAQQBBAEwAUQBCAGwAQQBIAEUAQQBJAEEAQQB5AEEAQwBrAEEASQBBAEIANwBBAEMAQQBBAGQAQQBCAG8AQQBIAEkAQQBiAHcAQgAzAEEAQwBBAEEASQBnAEIAcABBAEcANABBAGQAZwBCAGgAQQBHAHcAQQBhAFEAQgBrAEEAQwBBAEEAYwBBAEIAaABBAEgAawBBAGIAQQBCAHYAQQBHAEUAQQBaAEEAQQBpAEEAQwBBAEEAZgBRAEEASwBBAEYATQBBAFoAUQBCADAAQQBDADAAQQBWAGcAQgBoAEEASABJAEEAYQBRAEIAaABBAEcASQBBAGIAQQBCAGwAQQBDAEEAQQBMAFEAQgBPAEEARwBFAEEAYgBRAEIAbABBAEMAQQBBAGEAZwBCAHoAQQBHADgAQQBiAGcAQgBmAEEASABJAEEAWQBRAEIAMwBBAEMAQQBBAEwAUQBCAFcAQQBHAEUAQQBiAEEAQgAxAEEARwBVAEEASQBBAEEAawBBAEgATQBBAGMAQQBCAHMAQQBHAGsAQQBkAEEAQgBmAEEASABBAEEAWQBRAEIAeQBBAEgAUQBBAGMAdwBCAGIAQQBEAEUAQQBYAFEAQQBLAEEAQwBRAEEAWgBRAEIANABBAEcAVQBBAFkAdwBCAGYAQQBIAGMAQQBjAGcAQgBoAEEASABBAEEAYwBBAEIAbABBAEgASQBBAEkAQQBBADkAQQBDAEEAQQBXAHcAQgBUAEEARwBNAEEAYwBnAEIAcABBAEgAQQBBAGQAQQBCAEMAQQBHAHcAQQBiAHcAQgBqAEEARwBzAEEAWABRAEEANgBBAEQAbwBBAFEAdwBCAHkAQQBHAFUAQQBZAFEAQgAwAEEARwBVAEEASwBBAEEAawBBAEgATQBBAGMAQQBCAHMAQQBHAGsAQQBkAEEAQgBmAEEASABBAEEAWQBRAEIAeQBBAEgAUQBBAGMAdwBCAGIAQQBEAEEAQQBYAFEAQQBwAEEAQQBvAEEASgBnAEEAawBBAEcAVQBBAGUAQQBCAGwAQQBHAE0AQQBYAHcAQgAzAEEASABJAEEAWQBRAEIAdwBBAEgAQQBBAFoAUQBCAHkAQQBBAD0APQA=']
<dc.whcorp.lan> WINRM RESULT '<Response code 0, out "{"changed":false,"in", err "#< CLIXML\r\n<Objs Ver">'
<dc.whcorp.lan> WINRM CLOSE SHELL: 9C788938-97F0-4AC5-9B04-0F9981962A89
__dc.whcorp.lan | SUCCESS => {
    "changed": false,
    "invocation": {
        "module_args": {
            "data": "pong"
        }
    },
    "ping": "pong"__
}
META: ran handlers
META: ran handlers

__output with psrp module:__
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/will/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.3 (default, Dec 20 2019, 18:57:59) [GCC 8.3.0]
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
auto declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Parsed /etc/ansible/hosts inventory source with ini plugin
Loading callback plugin minimal of type stdout, v2.0 from /usr/local/lib/python3.7/dist-packages/ansible/plugins/callback/minimal.py
META: ran handlers
Using module file /usr/local/lib/python3.7/dist-packages/ansible/modules/windows/win_ping.ps1
Pipelining is enabled.
<dc.whcorp.lan> ESTABLISH PSRP CONNECTION FOR USER: ansible_svc@WHCORP.LAN ON PORT 5985 TO dc.whcorp.lan
<dc.whcorp.lan> PSRP OPEN RUNSPACE: auth=kerberos configuration=Microsoft.PowerShell endpoint=http://dc.whcorp.lan:5985/wsman
The full traceback is:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/ansible/executor/task_executor.py", line 146, in run
    res = self._execute()
  File "/usr/local/lib/python3.7/dist-packages/ansible/executor/task_executor.py", line 645, in _execute
    result = self._handler.run(task_vars=variables)
  File "/usr/local/lib/python3.7/dist-packages/ansible/plugins/action/normal.py", line 46, in run
    result = merge_hash(result, self._execute_module(task_vars=task_vars, wrap_async=wrap_async))
  File "/usr/local/lib/python3.7/dist-packages/ansible/plugins/action/__init__.py", line 923, in _execute_module
    res = self._low_level_execute_command(cmd, sudoable=sudoable, in_data=in_data)
  File "/usr/local/lib/python3.7/dist-packages/ansible/plugins/action/__init__.py", line 1071, in _low_level_execute_command
    rc, stdout, stderr = self._connection.exec_command(cmd, in_data=in_data, sudoable=sudoable)
  File "/usr/local/lib/python3.7/dist-packages/ansible/plugins/connection/psrp.py", line 408, in exec_command
    sudoable=sudoable)
  File "/usr/local/lib/python3.7/dist-packages/ansible/plugins/connection/__init__.py", line 34, in wrapped
    self._connect()
  File "/usr/local/lib/python3.7/dist-packages/ansible/plugins/connection/psrp.py", line 383, in _connect
    self.runspace.open()
  File "/usr/local/lib/python3.7/dist-packages/pypsrp/powershell.py", line 508, in open
    self.shell.open(options, open_content)
  File "/usr/local/lib/python3.7/dist-packages/pypsrp/shell.py", line 204, in open
    option_set=options)
  File "/usr/local/lib/python3.7/dist-packages/pypsrp/wsman.py", line 259, in create
    option_set, selector_set, timeout)
  File "/usr/local/lib/python3.7/dist-packages/pypsrp/wsman.py", line 378, in invoke
    response = self.transport.send(xml)
  File "/usr/local/lib/python3.7/dist-packages/pypsrp/wsman.py", line 711, in send
    self._send_request(prep_request, hostname)
  File "/usr/local/lib/python3.7/dist-packages/pypsrp/wsman.py", line 739, in _send_request
    self.connection_timeout, self.read_timeout
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 653, in send
    r = dispatch_hook('response', hooks, r, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/hooks.py", line 31, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pypsrp/negotiate.py", line 86, in response_hook
    response = self.handle_401(response, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pypsrp/negotiate.py", line 98, in handle_401
    auth_hostname, self.service, self.delegate, self.wrap_required
  File "/usr/local/lib/python3.7/dist-packages/pypsrp/spnego.py", line 146, in get_auth_context
    out_token = next(context_gen)
  File "/usr/local/lib/python3.7/dist-packages/pypsrp/spnego.py", line 379, in step
    out_token = self._context.step(in_token)
  File "<decorator-gen-15>", line 2, in step
  File "/home/will/.local/lib/python3.7/site-packages/gssapi/_utils.py", line 167, in check_last_err
    return func(self, *args, **kwargs)
  File "<decorator-gen-5>", line 2, in step
  File "/home/will/.local/lib/python3.7/site-packages/gssapi/_utils.py", line 127, in catch_and_return_token
    return func(self, *args, **kwargs)
  File "/home/will/.local/lib/python3.7/site-packages/gssapi/sec_contexts.py", line 521, in step
    return self._initiator_step(token=token)
  File "/home/will/.local/lib/python3.7/site-packages/gssapi/sec_contexts.py", line 542, in _initiator_step
    token)
  __File "gssapi/raw/sec_contexts.pyx", line 245, in gssapi.raw.sec_contexts.init_sec_context
gssapi.raw.misc.GSSError: Major (851968): Unspecified GSS failure.  Minor code may provide more information, Minor (2529638919): Server not found in Kerberos database__
__dc.whcorp.lan | FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""__
}

Dependencies:

will@ansible:~$ pip3 list
Package            Version
------------------ -------------
ansible            2.9.6
appdirs            1.4.3
asn1crypto         1.3.0
asysocks           0.0.2
certifi            2018.8.24
cffi               1.14.0
chardet            3.0.4
cryptography       2.6.1
decorator          4.3.0
distlib            0.3.0
entrypoints        0.3
filelock           3.0.12
gssapi             1.6.2
httplib2           0.11.3
idna               2.6
importlib-metadata 1.5.0
Jinja2             2.11.1
keyring            17.1.1
keyrings.alt       3.1.1
MarkupSafe         1.1.1
minikerberos       0.2.0
ntlm-auth          1.4.0
pip                20.0.2
pyasn1             0.4.8
pycparser          2.20
pycrypto           2.6.1
pycurl             7.43.0.2
PyGObject          3.30.4
pykerberos         1.2.1
pypsrp             0.4.0
PySimpleSOAP       1.16.2
python-apt         1.8.4.1
python-debian      0.1.35
python-debianbts   2.8.2
python-gssapi      0.6.4
pywinrm            0.4.1
pyxdg              0.25
PyYAML             5.3
reportbug          7.5.3-deb10u1
requests           2.21.0
requests-gssapi    1.2.0
requests-ntlm      1.1.0
SecretStorage      2.3.1
setuptools         40.8.0
six                1.12.0
urllib3            1.24.1
virtualenv         20.0.10
wheel              0.32.3
xmltodict          0.12.0
zipp               3.1.0

kinit working fine:
kinit -C ansible_svc@WHCORP.LAN
Password for ansible_svc@WHCORP.LAN:
will@ansible:~$ klist
Ticket cache: FILE:/tmp/krb5cc_1000
Default principal: ansible_svc@WHCORP.LAN

Valid starting       Expires              Service principal
19/03/2020 15:06:49  20/03/2020 01:06:49  krbtgt/WHCORP.LAN@WHCORP.LAN
        renew until 26/03/2020 15:06:45

**Comment by jborean93** [comment]
IIRC pypsrp uses a different default SPN than pywinrm, we set a default service part of `WSMAN` https://github.com/jborean93/pypsrp/blob/master/pypsrp/negotiate.py#L35 whereas pywinrm sets `HTTP`. You could using `HTTP` in Ansible by setting `ansible_psrp_negotiate_service: HTTP` as a connection var.

If that doesn't work then something else is going on.

**Comment by willofr** [comment]
Thank you your explanation !
Setting `ansible_psrp_negotiate_service: HTTP` fixed the problem.
