### ISSUE TITLE
WARNING_RECORD message KeyError leaves pool open

### ISSUE THREAD

**Issue by KKomarov** [jborean93/pypsrp#70]
Got such error while opening a connection to `outlook.office365.com` exchange server.

pypsrp == 0.4.0

	>  with RunspacePool(wsman, configuration_name='Microsoft.Exchange') as pool:

	test_psremote.py:16: 
	_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
	C:\Python37\lib\site-packages\pypsrp\powershell.py:200: in __enter__
		self.open()
	C:\Python37\lib\site-packages\pypsrp\powershell.py:513: in open
		responses.extend(self._receive())
	C:\Python37\lib\site-packages\pypsrp\powershell.py:637: in _receive
		return self._parse_responses(response, pipeline)

Attached file with responses: [responses-warning.txt](https://github.com/jborean93/pypsrp/files/4593029/responses-warning.txt)
As I can understand there is no pipeline created at the moment we receive warning message.

Warning message which caused KeyError
![image](https://user-images.githubusercontent.com/14128194/81690053-80b15580-9463-11ea-97a9-2359475e3bb1.png)

**Comment by yymax** [comment]
I can confirm this issue as well. The warning message is "Using New-PSSession with Basic Authentication is going to be deprecated soon". There is another PIPELINE_STATE message after it.  

I am no expert in psrp but the following monkey patch seems to fix the symptom. Not sure if there's more fundamental changes needed though. 

In powershell.py

>     def _parse_responses(self, responses, pipeline=None):
        messages = self._fragmenter.defragment(responses)

        response_functions = {
            # While the docs say we should verify, they are out of date with
            # the possible responses and so we will just ignore for now
            MessageType.SESSION_CAPABILITY: self._process_session_capability,
            MessageType.ENCRYPTED_SESSION_KEY:
                self._process_encrypted_session_key,
            MessageType.PUBLIC_KEY_REQUEST: self.exchange_keys,
            MessageType.RUNSPACEPOOL_INIT_DATA:
                self._process_runspacepool_init_data,
            MessageType.RUNSPACE_AVAILABILITY:
                self._process_runspacepool_availability,
            MessageType.RUNSPACEPOOL_STATE: self._process_runspacepool_state,
            MessageType.USER_EVENT: self._process_user_event,
            MessageType.APPLICATION_PRIVATE_DATA:
                self._process_application_private_data,
            MessageType.RUNSPACEPOOL_HOST_CALL:
                self._process_runspacepool_host_call,

            MessageType.ERROR_RECORD: self._process_error_record,
            MessageType.DEBUG_RECORD: self._process_debug_record,
            MessageType.VERBOSE_RECORD: self._process_debug_record,
            MessageType.WARNING_RECORD: self._process_warning_record,
            MessageType.PROGRESS_RECORD: self._process_info_record,
            MessageType.INFORMATION_RECORD: self._process_info_record,
            MessageType.PIPELINE_STATE: self._process_pipeline_state,
            MessageType.PIPELINE_OUTPUT: None,
            MessageType.PIPELINE_HOST_CALL: None,
        }

        if pipeline is not None:
            pipeline_response_functions = {
                # The Pipeline Output isn't processes and just returned back to
                # the receive caller
                MessageType.PIPELINE_OUTPUT: None,
                MessageType.ERROR_RECORD: pipeline._process_error_record,
                MessageType.PIPELINE_STATE: pipeline._process_pipeline_state,
                MessageType.DEBUG_RECORD: pipeline._process_debug_record,
                MessageType.VERBOSE_RECORD: pipeline._process_verbose_record,
                MessageType.WARNING_RECORD: pipeline._process_warning_record,
                MessageType.PROGRESS_RECORD: pipeline._process_progress_record,
                MessageType.INFORMATION_RECORD:
                    pipeline._process_information_record,
                MessageType.PIPELINE_HOST_CALL:
                    pipeline._process_pipeline_host_call,
            }
            response_functions.update(pipeline_response_functions)

        return_values = []
        for message in messages:
            response_function = response_functions[message.message_type]
            if response_function is not None:
                return_value = response_function(message)
                return_values.append((message.message_type, return_value))
            else:
                return_values.append((message.message_type, message))

        return return_values

    def _process_debug_record(self, message):
        log.debug(message.data)
        return message.data

    def _process_info_record(self, message):
        log.info(message.data)
        return message.data

    def _process_warning_record(self, message):
        log.warning(message.data)
        return message.data

    def _process_error_record(self, message):
        log.error(message.data)
        return message.data

    def _process_pipeline_state(self, message):
        log.debug("Received PipelineState with state: %d" % message.data.state)
        if message.data.error_record is not None:
            log.error(message.data.error_record)

**Comment by Nurtalf** [comment]
Same problem here, but I am not able to implement your fix @yymax 
I get error: 'RunspacePool' object has no attribute '_process_error_record'

**Comment by yymax** [comment]
@Nurtalf  do you mind to check if you have copied the functions (e.g. _process_debug_record, _process_info_record, etc.) correctly with proper indentation, and that they are part of the RunspacePool class? I also uploaded my version of the powershell.py source file here.
[powershell.zip](https://github.com/jborean93/pypsrp/files/4605132/powershell.zip)

**Comment by Nurtalf** [comment]
@yymax It is working now. I was editing the same methods in another class, not adding them in the the RunspacePool class. 
Appriciate the fix! Thanks!

**Comment by jborean93** [comment]
Thanks for the bug report, I was never aware that a warning could be sent at this moment, will have to add that functionality in a similar way to your monkeypatch.

**Comment by Gtrikoilis** [comment]
A friend of mine found quick one-liner solution for this  @truekonrads
in the powershell.py module 
patch line 681 to response_function = response_functions.get(message.message_type)

**Comment by jborean93** [comment]
Sorry for the delay I've fixed this issue in https://github.com/jborean93/pypsrp/pull/82 and will be in the upcoming 0.5.0 release. Just an FYI though it seems like Exchange Online no longer issues this warning so the current release will start working again. In any case if they do re-add one later on the 0.5.0 will be able to handle it.
