### ISSUE TITLE
Error execute powershel with  Python, but work with PowerShell

### ISSUE THREAD

**Issue by ximik666** [jborean93/pypsrp#72]
Hello. I execute this script from Powershell:
```
##Create credential and then insert password 
$cred = Get-Credential -Credential test.tld\test 

##connect to remote server
Enter-PSSession -Computername dc.test.tld -UseSSL -Authentication negotiate Credential $cred

#connect(hope) to another server from dc to test2
[dc.test.tld] Get-ADUser -server test2.test.tld -SearchBase "OU...." -Filter '(Name .......)' 

```

This script returns the values ​​I need.
But when I try to repeat this using Python and pypsrp does not get the hell out of connecting to test2.test.tld
```
from pypsrp.powershell import PowerShell, RunspacePool
from pypsrp.wsman import WSMan
SERVER = "dc.test.tld"
USER = "test.tld\\test"
PASSWORD = "password"
wsman = WSMan(SERVER, username=USER, auth="negotiate",encryption= "never",ssl=True,password=PASSWORD, cert_validation=False)
        with RunspacePool(wsman) as pool:
            ps = PowerShell(pool)
            ps.add_script(f'Get-ADUser -server test2.test.tld -SearchBase "OU...." -Filter '(Name .......)'')
            output = ps.invoke()
```

Here I get an error that the server `test2.test.tld` is not available.
Python script and Powershell run on the same computer
Thank you.

**Comment by jborean93** [comment]
There's a chance that on the Windows side it's utilising Kerberos delegation so the remote WinRM session is able to connect to another server.

Negotiate authentication on Linux is a lot more complicated but it's still potentially possible to achieve the same thing. What I recommend you try

* Setting the user in the UPN form `test@TEST.TLD`, GSSAPI on Linux requires the user in this form for Kerberos auth
* Potentially enforcing `auth='kerberos'` to make sure Kerberos is tried or at least error when it fails
* Make sure you have the Kerberos dependencies installed

If it works when connecting to the first host but still fails to run the script you may need to add `negotiate_kerberos_delegation=True` to the WSMan arguments to make sure a delegated ticket is retrieved.

**Comment by jborean93** [comment]
Closing as I hope that answered your question and I have not heard a response back.
