### ISSUE TITLE
How to collect Exchange Poweshell stdout

### ISSUE THREAD

**Issue by XityZhang** [jborean93/pypsrp#74]
Hey guys.I have some complex scene and I use local powershell script file in Exchange Server.
Then I use Django to receive frontend query and run appropriate script by pypsrp,but I cant receive the script stdout.
Such as there is a function that I make to obain mailgroup members. I have to recieve script stdout.
How can I do that?
thanks

**Comment by XityZhang** [comment]
Such as this powershell script
`Get-ADObject -Identity $User -Properties * | fl mail`
it works fine in ExchangePowershell Management but if I call this script by pypsrp, I receive None in output and stream.

**Comment by XityZhang** [comment]
for execute this Exchange Management Shell
`Get-DistributionGroup AllUsers | ForEach-Object {$_.AcceptMessagesOnlyFromSendersOrMembers} | ForEach-Object {$_.DistinguishedName}`

and I do this
`ps = PowerShell(pool)`
`script  = """
$username = username
$password = ConvertTo-SecureString password -AsPlainText -Force
$UserCredential = new-object -typename System.Management.Automation.PSCredential -argumentlist $username, $password
$Session = (New-PSSession -configurationname Microsoft.Exchange -connectionURI http://hostname/PowerShell -Authentication Kerberos -Credential $UserCredential)
Import-PSSession $Session
"""`

- 

then I add script and cmdlet
`ps.add_script(script)`

`ps.add_script("Get-DistributionGroup").add_argument("AllUsers")`
`ps.add_cmdlet("ForEach-Object").add_argument("{$_.AcceptMessagesOnlyFromSendersOrMembers}")`
`ps.add_cmdlet("ForEach-Object").add_argument("{$_.DistinguishedName}")`

`output = ps.invoke()`

but I got null list
`['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '']`

**Comment by jborean93** [comment]
I would recommend you try a script like this

```python
from pypsrp.complex_object import PSCredential


with RunspacePool(wsman) as pool:
    pool.exchange_keys()  # Allows you to exchange SecureString securely

    cred = PSCredential(username='username', password='password')

    ps = PowerShell(pool)

    # Securely send the PSCredential across, this is encrypted over the wire.
    ps.add_cmdlet('Set-Variable').add_parameters({'Name': 'UserCredential', 'Value': cred}).add_statement()

    ps.add_script("""
$Session = (New-PSSession -configurationname Microsoft.Exchange -connectionURI http://hostname/PowerShell -Authentication Kerberos -Credential $UserCredential)
Import-PSSession $Session
""").add_statement()  # add_statement() isn't necesary but it helps to separate commands

    ps.add_cmdlet('Get-DistributionGroup').add_argument('AllUsers')
    ps.add_cmdlet('ForEach-Object').add_argument('{$_.AcceptMessagesOnlyFromSendersOrMembers}')
    ps.add_cmdlet('Select-Object').add_parameter('ExpandProperty', 'DistinguishedName')

    output = ps.invoke()
```

A few things that it changes

* Instead of sending your credentials in the scriptblock as plaintext we send an actual PSCredential across the wire
    * This saves you from having your credentials logged using PowerShell's scriptblock logger if enabled
    * The PSCredential sends an encrypted string for the password so you don't have to worry about that being in plaintext
    * Also simplifies the initial session setup script as you don't need to create the credential there, the variable is already set
* I've changed the final command to be

```powershell
Get-DistributionGroup |
    ForEach-Object {$_.AcceptMessagesOnlyFromSendersOrMembers} |
    Select-Object -ExpandProperty DistinguishedName
```

This should hopefully send across the `DistinguishedName` as an individual value.

If you are still seeing an empty string in the output maybe make sure that it is an empty string. Try doing

```python
isinstance(output[0], str)
vars(output[0])
```

The first will see if it's actually a string, the 2nd will show other properties that may contain the data you want if the value is not a string.

**Comment by XityZhang** [comment]
> I would recommend you try a script like this
> 
> ```python
> from pypsrp.complex_object import PSCredential
> 
> 
> with RunspacePool(wsman) as pool:
>     pool.exchange_keys()  # Allows you to exchange SecureString securely
> 
>     cred = PSCredential(username='username', password='password')
> 
>     ps = PowerShell(pool)
> 
>     # Securely send the PSCredential across, this is encrypted over the wire.
>     ps.add_cmdlet('Set-Variable').add_parameters({'Name': 'UserCredential', 'Value': cred}).add_statement()
> 
>     ps.add_script("""
> $Session = (New-PSSession -configurationname Microsoft.Exchange -connectionURI http://hostname/PowerShell -Authentication Kerberos -Credential $UserCredential)
> Import-PSSession $Session
> """).add_statement()  # add_statement() isn't necesary but it helps to separate commands
> 
>     ps.add_cmdlet('Get-DistributionGroup').add_argument('AllUsers')
>     ps.add_cmdlet('ForEach-Object').add_argument('{$_.AcceptMessagesOnlyFromSendersOrMembers}')
>     ps.add_cmdlet('Select-Object').add_parameter('ExpandProperty', 'DistinguishedName')
> 
>     output = ps.invoke()
> ```
> 
> A few things that it changes
> 
> * Instead of sending your credentials in the scriptblock as plaintext we send an actual PSCredential across the wire
>   
>   * This saves you from having your credentials logged using PowerShell's scriptblock logger if enabled
>   * The PSCredential sends an encrypted string for the password so you don't have to worry about that being in plaintext
>   * Also simplifies the initial session setup script as you don't need to create the credential there, the variable is already set
> * I've changed the final command to be
> 
> ```powershell
> Get-DistributionGroup |
>     ForEach-Object {$_.AcceptMessagesOnlyFromSendersOrMembers} |
>     Select-Object -ExpandProperty DistinguishedName
> ```
> 
> This should hopefully send across the `DistinguishedName` as an individual value.
> 
> If you are still seeing an empty string in the output maybe make sure that it is an empty string. Try doing
> 
> ```python
> isinstance(output[0], str)
> vars(output[0])
> ```
> 
> The first will see if it's actually a string, the 2nd will show other properties that may contain the data you want if the value is not a string.

thanks for replying!
I will try it and reply late!

**Comment by XityZhang** [comment]
After a lot of trying, I didn't get the results I wanted, and we changed the way the powershell was used to make the project go smoothly. Thank you!
