### ISSUE TITLE
Relevance of CTRL_C while invoking process

### ISSUE THREAD

**Issue by Rohith050** [jborean93/pypsrp#76]
One of the examples in README section has the below code

`from pypsrp.shell import Process, SignalCode, WinRS
from pypsrp.wsman import WSMan

wsman = WSMan("server", ssl=False, auth="basic", encryption="never",
              username="vagrant", password="vagrant")

with WinRS(wsman) as shell:
    process = Process(shell, "dir")
    process.invoke()
    process.signal(SignalCode.CTRL_C)`

I was wondering why CTRL_C is issues after invoking the process? Should this be done for all invokes? 
Thanks in advance

**Comment by jborean93** [comment]
I actually believe there's a mistake in the docs, the signal used here should really be `SignalCode.TERMINATE` as that is what the [docs in MS-WSMV](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-wsmv/4d6a53ab-3db9-4219-b06d-2643e9dda9a0). According to those docs the TERMINATE signal is used to

> This control code is sent by the client to acknowledge receipt of the end of the command output from the service and to clean up any resources associated with command execution. Because the service might have to cache this information until it knows that the client has received the entire stream, the client MUST send this before a new command can be executed.

This seems to indicate that you should be sending that signal when running multiple commands on the same shell. This allows the shell to cleanup any running running command associated with that process. When testing this doesn't seem to be required so it could potentially just be a recommendation from Microsoft in case things went wrong. I personally would still run the `TERMINATE` code in case there are some underlying resources that still need to be cleaned up.

**Comment by jborean93** [comment]
I hope that answers your question, closing the issue now.
