### ISSUE TITLE
Redirecting stderr to stdout

### ISSUE THREAD

**Issue by Rohith050** [jborean93/pypsrp#84]
Hi,
Is it possible to redirect stderr output to stdin?
While creating the shell(WinRs), i have provided the output streams as 'stdout'. But still process always gives me errors in stderr

```
with WinRS(self.wsman, output_streams='stdout') as shell:

            process = Process(shell, i.get('cmd'))
            process.begin_invoke()  # start the invocation and return immediately
            process.poll_invoke()  # update the output stream
            process.end_invoke()
```

BTW, thanks for the great library

**Comment by jborean93** [comment]
When you use WinRS you are effectively running it in a cmd shell so you need to use the redirection when you call the process. Setting `output_streams` when creating the WinRS object isn't right and it's only there for custom shells like the one PowerShell remoting requires.

Basically just change your process = line to `process = Process(shell, 'my.exe 2>&1')`.
