### ISSUE TITLE
How do colleagues get multiple attributes

### ISSUE THREAD

**Issue by daidechong** [jborean93/pypsrp#88]
I want to get multiple attributes when I query, just like in Ps

`Get-Mailbox -identity james | Format-List Guid, ServerName, DisplayName`

thanks

**Comment by jborean93** [comment]
This library can execute your PowerShell script just like normal, have a look at the `execute_ps` examples in the [High Level API docs](https://github.com/jborean93/pypsrp#examples). If you are asking how to use `Get-Mailbox` that's a question that should be asked somewhere else. This library just executes the code.
