### ISSUE TITLE
Interactive Powershell Session

### ISSUE THREAD

**Issue by gthieleb** [jborean93/pypsrp#89]
Hi, thanks for this beautiful library. Executing remote commands and powershell functions works like a charm.
I already use Ansible together with winrm successfully and I am interested to enhance usecase to also manage some windows instances interactively from my Ubuntu box. Goal is to mimic behavior of [Enter-PSSession](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/enter-pssession?view=powershell-7). Is this possible using `pypsrp`? Install the native Powershell in Ubuntu seems bloated to me (at least for this usecase) and is currently not supported for 20.04.

**Comment by jborean93** [comment]
It is technically possible but not implemented. You would have to implement the interactive console to deal with this but theoretically it can be done.

While this would be considered a feature, I don't have any capacity or time to implement it anytime soon. As such I am going to close the issue. If you are interested in developing the code you are more than welcome to submit a PR.
