### ISSUE TITLE
Problem with encoding en execute_ps in case of OS French (special charaters)

### ISSUE THREAD

**Issue by DahmounLahcen** [jborean93/pypsrp#94]
As you did in execute_cmd function (code=437) !, it is about the the problem of encoding! 
how we can do that en execute_os function

**Comment by jborean93** [comment]
What's the particular issue you are facing? There's no encoding method in `execute_ps` because it operates on actual strings  and so it isn't needed. The `execute_cmd` function operates over bytes so it needs an encoding to convert the strings to bytes and back again.

**Comment by DahmounLahcen** [comment]
When I use execute_ps function ; for example execute_ps('net accounts | select-string "Dur" '); i get the the output like the flowing : 
   Du**r,**e du verrouillage : 30 ;
But, I want to be : Dur**é**e du verrouillage ...

**Comment by jborean93** [comment]
Thanks for the clarification and I think I may know why this is happening. The `net accounts` command is calling `net.exe` and that outputs your text using 1 set of encoding and PowerShell needs to read that as a string which is happening as another encoding. This results in the non-ASCII strings like `é` being seen as different characters and therefore the string that PowerShell has being wrong. For example say `net.exe` outputs `café` here is the flow from that output into PowerShell

* It needs to convert it's string representation to bytes and output that onto the console's STDOUT
    * `caf` are fine because they are pure ASCII characters but `é` can be problematic as it isn't ASCII
    * Depending on the console encoding you could get `é` represented with the following byte(s)

| Encoding/Codepage | Bytes |
| - | - |
| CP437 | 0x82 |
| Windows 1252 | 0xE9 |
| UTF-8 | 0xC3 0xA9 |

* PowerShell needs to read those bytes using a set encoding to be able to convert it back to a string
    * If PowerShell uses the same encoding that `net accounts` used then the string will be the same
    * If PowerShell uses a different encoding then those bytes could now represent different characters or `?` if it is unknown
* Those strings are then output as CLIXML to Python running `pypsrp` but this operates on the string level so no encoding issues should appear here

While I abhor a blunt hammer to try and fix this issue, the story around PowerShell and native application encoding is a complex and full of weird edge cases. What I recommend you do is to force the output/input/console encoding to be UTF-8 and hope that fixes your issue

```python
execute_ps('''$OutputEncoding = [Console]::InputEncoding = [Console]::OutputEncoding = [System.Text.UTF8Encoding]::new()
net accounts''')
```

This wil set the following elements to use UTF-8 encoding which hopefully will solve your problems as it will all be on UTF-8

* `$OutputEncoding` - Not really needed in your case but this controls how PowerShell encodes bytes sent to native applications
    * `"some string" | my_app.exe` - Controls how `"some string"` is encoded to bytes and sent to `my_app.exe`
* `[Console]::InputEncoding` - Controls the encoding that the current control reads data at
* `[Console]::OutputEncoding` - Controls the encoding the console will output data as

The last one is what "should" fix your problem and force `net` to output as UTF-8 and PowerShell to read as UTF-8 but it doesn't hurt to set the others to keep things all in sync. Let me know if that solves your problem for you.

**Comment by DahmounLahcen** [comment]
I know, I did that before, and the function return said that the function is not finished properly (RC= False), that s means some problem is occurred.

**Comment by jborean93** [comment]
`execute_ps` returns 3 things as a tuple in this order

* `output`: The data from the output stream as a string
* `streams`: All the streams and their values from the script that was run
* `has_errors`: A bool that indicates whether there was an error reported (True) or not (False)

If by `RC = False` you meant the 3rd value in the return tuple then that means there wasn't an error that occurred, or at least that was reported to PowerShell.

**Comment by DahmounLahcen** [comment]
Sorry, it  returns RC=1, which means there was an error reported, Yeah execute_ps return a tuple .

**Comment by jborean93** [comment]
If you are getting an rc value back in the return tuple then you are calling `execute_cmd` and not `execute_ps`. Can you share the full code (without credentials) that you are running and the output you get back.

**Comment by DahmounLahcen** [comment]
Okey; [
![Capture](https://user-images.githubusercontent.com/41157199/99371724-9050a180-28bf-11eb-90af-ef627d05306a.PNG)
](url)

the output : 
![ssss](https://user-images.githubusercontent.com/41157199/99371759-9c3c6380-28bf-11eb-985f-92499ca00b8b.PNG)

**Comment by jborean93** [comment]
Ok the rc is 1 because you are converting the book to an int with `%d`. You need to look into the streams like `stderr.error` to get the error message. The reason why there’s an error is because your syntax is wrong. You need to put your `net accounts` on a new line (like my example) or separate it from the first command with `;`. Remember what you execute here must be valid powershell that you can run in a script.

**Comment by DahmounLahcen** [comment]
yeah, RC = 1, 1 means true. Even though I put a separator ( _;_) on it, i get the same return.

![Capture](https://user-images.githubusercontent.com/41157199/99376482-4cf93180-28c5-11eb-8a6f-048ba2fb73c8.PNG)

**Comment by jborean93** [comment]
The next step would be to see what the error was by printing each error record in the error stream.

```python
for error_record in stderr.error:
    print(str(error_record))
```

**Comment by DahmounLahcen** [comment]
OK,  I get the flowing output: 

![Capture](https://user-images.githubusercontent.com/41157199/99377610-b2015700-28c6-11eb-9eb0-739d8f7cd725.PNG)

**Comment by jborean93** [comment]
The output is the exact same as before, did you try to add what I had? This is what happens when I try to run with something that isn't correct

```python
from pypsrp.client import Client

with Client('server') as c:
    output, streams, had_errors = c.execute_ps('OutputEncoding = [Console]::InputEncoding = [Console]::OutputEncoding = [System.Text.UTF8Encoding]::new() net accounts')
    for error in streams.error:
        print(str(error))
```

The output contains

```
At line:1 char:105
+ ...  [Console]::OutputEncoding = [System.Text.UTF8Encoding]::new() net ac ...
+                                                                  ~
An expression was expected after '('.
```

Telling me that my syntax was incorrect.

**Comment by DahmounLahcen** [comment]
Yeah, for the flowing code:
`from pypsrp.client import Client

with Client('server') as c:
    output, streams, had_errors = c.execute_ps('OutputEncoding = [Console]::InputEncoding = [Console]::OutputEncoding = [System.Text.UTF8Encoding]::new() net accounts')
    for error in streams.error:
        print(str(error))`
I get the flowing output: 

![Capture](https://user-images.githubusercontent.com/41157199/99389448-5ee3d000-28d7-11eb-9b82-00e5d4f02fe8.PNG)

**Comment by jborean93** [comment]
What I’m saying is you need to look at the error record and fix up what the error is saying. The PowerShell you have isn’t valid and pypsrp cannot do anything to change that.
