### ISSUE TITLE
Question executing multiple commands in the same pipeline

### ISSUE THREAD

**Issue by telematico** [jborean93/pypsrp#95]
Hello:

This is a question, not a issue.

I'm trying to execute multiple commands in the same shell session and I can't find a way. What I'm trying to do is:
client.execute_ps('''$var="hello"''')
client.execute_ps('''Write-Host $var''')
but in the second execution I can not access to $var value. 

I understand each execution is in a complete different environment, but I need to execute commands like if I was in a real powershell session.

Is there any way of doing this?

thanks!

**Comment by jborean93** [comment]
Not with the high level API, each call runs in a completely new runspace so it does not have access to any of the previous state. If you want to run mutliple commands you can easily just run them on newlines like

```python
client.execute_ps('''
$var = "hello"
Write-Host $var
''')
```

If you are wanting to output data back and forth between Python and PowerShell you will have to use the low level API.

```python
from pypsrp.wsman import WSMan
from pypsrp.powershell import RunspacePool, PowerShell

with WSMan('server') as wsman, RunspacePool(wsman) as rp:
    ps = PowerShell(rp)
    ps.add_script('$var = "Hello"')
    ps.invoke()

    ps = PowerShell(rp)
    ps.add_script('Write-Output $var')
    print(ps.invoke())
```

Be careful with the low level API, objects are output as actual PowerShell objects and the current interface for dealing with these is a bit rudimentary. You might want to ensure you convert them to a string or use `| ConvertTo-Json`  so you can easily deal with the objects back in the Python land.
