### ISSUE TITLE
how to add command Get-Maibox and Select 

### ISSUE THREAD

**Issue by altamiro** [jborean93/pypsrp#96]
Hi

how to add this command "Get-Mailbox -ResultSize 10 | Select id, RecipientType, RecipientTypeDetails, PrimarySmtpAddress" using pypsrp and getting the return

My code that I use as an example

`
       wsman = WSMan(server="outlook.office365.com", port=443, path="powershell-liveid",
                      auth="basic", username=username, password=password, cert_validation=False)

        with RunspacePool(wsman, configuration_name="Microsoft.Exchange") as pool:

            ps = PowerShell(pool)
            ps.add_cmdlet("Get-Mailbox").add_parameter("ResultSize",10)
            output = ps.invoke()

            print ("==============================================")
            if ps.had_errors:
                print("ERROR:\n%s" % "\n".join([str(s) for s in ps.streams.error]))
            else:
                print("OUTPUT:\n%s" % "\n".join([str(s) for s in output]))
            print("==============================================")
`

Thanks for the help

**Comment by jborean93** [comment]
PowerShell returns an object back with your properties and by default Python doesn't know how to format them. You can access those properties under `output[0].extended_properties` or `output[0].adapted_properties`. Both of those attributes are a dictionary with the key being the name of the property and the value being the value. I've got plans to try and make all this easier to manage within python but right now that's in the really early stages.

So you have 3 options

* Get the property values manually in the GenericComplexObject in your output
* Wrap your output in `ConvertTo-Json` so the output is a string that you can load into Python
* Wrap you command in `Invoke-Expression` so PowerShell formats the output for you.

The last option is what is done for the high level client https://github.com/jborean93/pypsrp/blob/c70487480cbb651a89ee7d3efe5dfd21014ecc92/pypsrp/client.py#L212-L215. It wraps the command, in your case `Get-Mailbox -ResultSize 10` inside Invoke-Expression and makes sure the output from that is a string to mimick what PowerShell would usually display on it's console.

**Comment by zhaohr901217** [comment]
I am the local Exchange, how should I access Exchange shell to make the get-Mailbox work.

Python:
wsman = WSMan(server="ex.test.com",port=80,path="powershell",username=username, password=pwd,ssl=False)
_Error:SpnegoError (4294967295): [WinError -2146893039] 无法为身份验证与颁发机构取得联系。, Context: Processing security token_

Powershell:
New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri "http://ex.test.com/powershell/" -Credential $Credentials -Authentication Kerberos -Name ex

**Comment by jborean93** [comment]
@K-V4 the error you have is [SEC_E_NO_AUTHENTICATING_AUTHORITY 0x80090311](https://docs.microsoft.com/en-us/windows/win32/secauthn/initializesecuritycontext--general)

> No authority could be contacted for authentication. The domain name of the authenticating party could be wrong, the domain could be unreachable, or there might have been a trust relationship failure.

What this usually means is the process cannot reach the active directory domain controller and start the Kerberos authentication process. I'm not sure why PowerShell itself is working.
